on: [push, pull_request]

name: Tests

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - 1.63.0
    steps:
      - uses: r7kamura/rust-problem-matchers@v1

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install toolchain
        run: |
          rustup toolchain install ${{ matrix.rust }} --profile=minimal
          rustup override set ${{ matrix.rust }}

      - name: Check Fmt
        if: matrix.rust == 'stable'
        run: cargo fmt --check

      - name: Check Lints (all features)
        if: matrix.rust == 'stable'
        run: cargo clippy --tests --features ${{ env.all_features }}

      - name: Test (default features)
        run: cargo test

      - name: Test (no default features)
        run: cargo test --no-default-features

      - name: Test (libm only)
        run: cargo test --no-default-features --features "libm"

      - name: Test (schema features subset)
        if: matrix.rust == 'stable'
        run: cargo test --features "std,schemars"

      - name: Test (rand features subset)
        if: matrix.rust == 'stable'
        run: cargo test --features "rand,randtest"

      - name: Test (all features)
        if: matrix.rust == 'stable'
        run: cargo test --features ${{ env.all_features }}

env:
  all_features: "arbitrary,bytemuck,rand,randtest,serde,schemars,proptest,rkyv,rkyv_ck,speedy"
